#!/usr/bin/env python3

import subprocess
import sys

def calculate_product(*args):
    if len(args) != 3:
        count = 0
        num2 = 1
        for a in args:
            if count > 1:
                num2 *= a
            count += 1
    else:
        num2 = args[2]

    num1 = args[1]
    num = str(args[0]).replace(':', '=')

    if num2 > num1:
        num1, num2 = num2, num1

    print(f"{num}{num1}*{num2}")

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line.strip())
            result = subprocess.check_output(["factor", str(number)]).decode("utf-8").split()[1:]
            calculate_product(*result)
except FileNotFoundError:
    print(f"Error: File '{sys.argv[1]}' not found.")
    sys.exit(1)
except ValueError:
    print("Error: Invalid number in the file.")
    sys.exit(1)
except subprocess.CalledProcessError:
    print("Error: 'factor' command not found. Please ensure it is installed on your system.")
    sys.exit(1)

