#!/usr/bin/env python3

import sys

def factorize(n):
    factors = []
    for i in range(2, n + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    return factors

def check_factorization(n, factors):
    num1 = min(factors)
    num2 = n // num1
    print(f"{n}={num1}*{num2}")

if len(sys.argv) != 2:
    print('Usage: factors <file>')
    sys.exit(1)

try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line.strip())
            factors_list = factorize(number)
            check_factorization(number, factors_list)
except FileNotFoundError:
    print(f"Error: File '{sys.argv[1]}' not found.")
    sys.exit(1)
except ValueError:
    print("Error: Invalid number in the file.")
    sys.exit(1)

